HEAD-1026 on RHEL vm hosts , /lib/smartdc/set-root-authorized-keys doesn't work on the first try

diff --git a/guest/set-root-authorized-keys b/guest/set-root-authorized-keys
--- a/guest/set-root-authorized-keys
+++ b/guest/set-root-authorized-keys
@@ -1,16 +1,31 @@
 #!/bin/bash
 #
-# Copyright (c) 2011 Joyent Inc., All rights reserved.
+# Copyright (c) 2012 Joyent Inc., All rights reserved.
 #
 
+set -x
+
 if [[ ! -f /root/.ssh/authorized_keys ]]; then
-    authorized_keys=$(/lib/smartdc/mdata-get root_authorized_keys)
-    if [[ -n ${authorized_keys} ]]; then
-        mkdir -p /root/.ssh
-        echo "${authorized_keys}" > /root/.ssh/authorized_keys
-        chmod 700 /root/.ssh
-        chmod 600 /root/.ssh/authorized_keys
-    fi
+    i=0
+    while [ $i -le 3 ]; do
+        sleep 3 
+
+        authorized_keys=$(/lib/smartdc/mdata-get root_authorized_keys)
+
+	echo "${authorized_keys}" | egrep -s "Error getting metadata"
+	if [ $? -ne 0 ]; then
+            mkdir -p /root/.ssh
+            echo "${authorized_keys}" > /root/.ssh/authorized_keys
+            chmod 700 /root/.ssh
+            chmod 600 /root/.ssh/authorized_keys
+            exit 0
+	fi
+
+        date >>/root/.ssh/debuglog 
+        echo "debug: set-root-authorized-keys, failure or timeout...." \
+            >> /root/.ssh/debuglog 
+        ((i++))
+    done
 fi
 
 exit 0
