HEAD-1247 system should try to boot into single-user recovery mode if it reboots in the middle of an upgrade

diff --git a/overlay/lib/svc/method/fs-joyent b/overlay/lib/svc/method/fs-joyent
--- a/overlay/lib/svc/method/fs-joyent
+++ b/overlay/lib/svc/method/fs-joyent
@@ -144,6 +144,15 @@ fi
 # The rest only applies to the headnode
 /bin/bootparams | grep "^headnode=true" >/dev/null || exit $SMF_EXIT_OK
 
+# If we rebooted during an upgrade, we're in deep trouble.
+if [ -d /var/upgrade_in_progress ]; then
+    echo "ERROR: An upgrade was in progress when the system rebooted." \
+        >/dev/console
+    echo "       The system is in an indeterminate state, unable to continue." \
+        >/dev/console
+    exit $SMF_EXIT_ERR_FATAL
+fi
+
 USBMOUNTPOINT=/mnt/`svcprop -p "joyentfs/usb_mountpoint" ${SMF_FMRI}`
 COPYINPOINT=`svcprop -p "joyentfs/usb_copy_path" ${SMF_FMRI}`
 DEBUG=`svcprop -p "joyentfs/debug" ${SMF_FMRI}`
