OS-967 problems with 'zfs get' and mount 'Device busy'

diff --git a/overlay/lib/svc/method/fs-joyent b/overlay/lib/svc/method/fs-joyent
--- a/overlay/lib/svc/method/fs-joyent
+++ b/overlay/lib/svc/method/fs-joyent
@@ -47,6 +47,35 @@ function destroy_zpools
     done
 }
 
+function mount_zfs
+{
+    local dataset=$1
+    local mountpoint=$2
+    local output=
+
+    #
+    # Try to mount the ZFS dataset.  If the mountpoint is busy, wait five
+    # seconds and try again.  Fail if the mount attempt returns EBUSY three
+    # consecutive times.
+    #
+    for i in {1..3}; do
+        output=$(mount -F zfs ${dataset} ${mountpoint} 2>&1)
+        if [[ $? -eq 0 ]]; then
+            break
+        fi
+
+        if [[ ${output} -eq "mount failed: Device busy" ]]; then
+            sleep 5
+        else
+            echo ${output} 1>&2
+            return
+        fi
+    done
+
+    # The mount attempt must have failed
+    echo ${output} 1>&2
+}
+
 /bin/bootparams | grep "^noimport=true" >/dev/null
 if [ $? -ne 0 ]; then
     # If the zpool doesn't exist, then there's nothing to mount.
@@ -77,15 +106,15 @@ if [ $? -ne 0 ]; then
     # For the system zpool, mount and configure all system datasets
     zpool status -v ${SYS_ZPOOL}
     if [ $? -eq 0 ]; then
-        mount -F zfs ${SYS_ZPOOL}/var /var
-        mount -F zfs ${SYS_ZPOOL}/config /etc/zones
-        mount -F zfs ${SYS_ZPOOL}/opt /opt
+        mount_zfs ${SYS_ZPOOL}/var /var
+        mount_zfs ${SYS_ZPOOL}/config /etc/zones
+        mount_zfs ${SYS_ZPOOL}/opt /opt
         mkdir -p /opt/smartdc/agents/smf
         mount -O -F lofs /var/svc/manifest/site /opt/smartdc/agents/smf
 
         if [[ -n $(/bin/bootparams | grep '^headnode=true') ]]; then
             mkdir /usbkey
-            mount -F zfs ${SYS_ZPOOL}/usbkey /usbkey
+            mount_zfs ${SYS_ZPOOL}/usbkey /usbkey
         fi
 
         swap -a /dev/zvol/dsk/${SYS_ZPOOL}/swap || \
